save_dir: /data/PFL-DocVQA/models/
model_name: VT5
model_weights: rubentito/vt5-base-spdocvqa
max_input_tokens: 512
device: cuda
seed: 42

visual_module:
  model: dit
  model_weights: microsoft/dit-base-finetuned-rvlcdip
  finetune: False

training_parameters:
  lr: 2e-4  # 2e-4 default, 1e-3 for LoRA
  batch_size: 2
#  warmup_iterations: 1000
  train_epochs: 100

dp_parameters:
  providers_per_iteration: 415
  total_providers: 4149
  sensitivity: 2
  noise_multiplier: 0.9368896484375
